---
owner: code-agent
repo_url: https://github.com/geraldthewes/video-transcription-batch.git
git_ref: main
dockerfile_path: docker/Dockerfile
image_name: video-transcription-batch
registry_url: registry.cluster:5000
resource_limits:
  cpu: "2000"      # 2000 MHz (2 CPU cores)
  memory: "16384"  # (16 GB RAM)
  disk: "20480"    # 20480 MB (20 GB disk)
