owner: code-agent
repo_url: https://github.com/geraldthewes/video-transcription-batch.git
git_ref: main
dockerfile_path: docker/Dockerfile
image_name: video-transcription-batch
image_tags:
  - latest
registry_url: registry.cluster:5000
test:
  entry_point: true
  gpu_required: true
  env:
    S3_TRANSCRIBER_BUCKET: "ai-storage"
    S3_TRANSCRIBER_PREFIX: "transcriber"
    S3_JOB_ID: "18517e9c-f624-4a16-bc10-a9236dbea7e1"
    OLLAMA_HOST: "http://10.0.1.12:11434"
    AWS_REGION: "us-east-1"
    S3_ENDPOINT: "http://cluster00.cluster"
    NVIDIA_VISIBLE_DEVICES: "all"
  vault_policies: ["transcription-policy"]
  vault_secrets:
  - path: "secret/data/aws/transcription"
    fields:
      access_key:  "AWS_ACCESS_KEY_ID"
      secret_key: "AWS_SECRET_ACCESS_KEY"
  - path: "secret/data/hf/transcription"
    fields:
      token: "HF_TOKEN"
resource_limits:
  build:
    cpu: "8000"
    memory: "16384"
    disk: "20480"
  test:
    cpu: "8000"
    memory: "16384"
    disk: "10240"
